import "@/assets/style/globals.css";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({children}) => {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main>{children}</main> 
      </body>
    </html>
  )
}

export default MainLayout;
