import "@/assets/style/globals.css";
import AuthProvider from "@/components/AuthProvider";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({children}) => {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <Navbar/>
          <main>{children}</main>
          <Footer/>
        </body>
      </html>
    </AuthProvider>
  )
}

export default MainLayout;